version: '3'

services:
  logging-service:
    container_name: logging_service

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./:/root/go/src/github.com/poc/logging-service

    ports:
      - '8080:8080'

